In [1]:
import tensorflow as tf
import tf2onnx
from tensorflow.keras.models import load_model, Model
import onnx

In [4]:
import torch

In [1]:
import timm

c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_validation.py:26: UserWarning: Unsupported Windows version (11). ONNX Runtime supports Windows 10 and above, only.
  warnings.warn(


In [2]:
timm.__version__

'0.4.5'

In [6]:
model = torch.load('model_weights/enet_b0_7.pt')

In [ ]:
timm.create_model('efficientnet_b0')

In [32]:
model = timm.create_model('efficientnet_b0')

EfficientNet(
  (conv_stem): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
  (bn1): BatchNormAct2d(
    32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True
    (drop): Identity()
    (act): SiLU(inplace=True)
  )
  (blocks): Sequential(
    (0): Sequential(
      (0): DepthwiseSeparableConv(
        (conv_dw): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
        (bn1): BatchNormAct2d(
          32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True
          (drop): Identity()
          (act): SiLU(inplace=True)
        )
        (se): SqueezeExcite(
          (conv_reduce): Conv2d(32, 8, kernel_size=(1, 1), stride=(1, 1))
          (act1): SiLU(inplace=True)
          (conv_expand): Conv2d(8, 32, kernel_size=(1, 1), stride=(1, 1))
          (gate): Sigmoid()
        )
        (conv_pw): Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn2): BatchNormAct2d(
      

In [31]:
timm.list_models()[200:]

['edgenext_xx_small',
 'efficientformer_l1',
 'efficientformer_l3',
 'efficientformer_l7',
 'efficientformerv2_l',
 'efficientformerv2_s0',
 'efficientformerv2_s1',
 'efficientformerv2_s2',
 'efficientnet_b0',
 'efficientnet_b0_g8_gn',
 'efficientnet_b0_g16_evos',
 'efficientnet_b0_gn',
 'efficientnet_b1',
 'efficientnet_b1_pruned',
 'efficientnet_b2',
 'efficientnet_b2_pruned',
 'efficientnet_b3',
 'efficientnet_b3_g8_gn',
 'efficientnet_b3_gn',
 'efficientnet_b3_pruned',
 'efficientnet_b4',
 'efficientnet_b5',
 'efficientnet_b6',
 'efficientnet_b7',
 'efficientnet_b8',
 'efficientnet_cc_b0_4e',
 'efficientnet_cc_b0_8e',
 'efficientnet_cc_b1_8e',
 'efficientnet_el',
 'efficientnet_el_pruned',
 'efficientnet_em',
 'efficientnet_es',
 'efficientnet_es_pruned',
 'efficientnet_l2',
 'efficientnet_lite0',
 'efficientnet_lite1',
 'efficientnet_lite2',
 'efficientnet_lite3',
 'efficientnet_lite4',
 'efficientnetv2_l',
 'efficientnetv2_m',
 'efficientnetv2_rw_m',
 'efficientnetv2_rw_s',
 'eff

In [19]:
!pip install timm

   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   --- ------------------------------------ 0.2/2.2 MB 5.9 MB/s eta 0:00:01
   ------------ --------------------------- 0.7/2.2 MB 8.5 MB/s eta 0:00:01
   ---------------- ----------------------- 0.9/2.2 MB 7.1 MB/s eta 0:00:01
   ------------------------------ --------- 1.7/2.2 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------  2.2/2.2 MB 10.2 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 9.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/388.9 kB ? eta -:--:--
   --------------------------------------- 388.9/388.9 kB 12.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/289.4 kB ? eta -:--:--
   ---------------------------------------- 289.4/289.4 kB 9.0 MB/s eta 0:00:00
   ---------------------------------------- 0.0/172.0 kB ? eta -:--:--
   --------------------------------------- 172.0/172.0 kB 10.1 MB/s eta 0:00:00
  Attempting uninstal

In [17]:
model=load_model('model_weights/mobilenet_7.h5')
model.get_weights()[0].shape

(3, 3, 3, 32)

In [5]:
type(model)

keras.src.models.functional.Functional

In [8]:
tf.saved_model.save(model, '.')

TypeError: this __dict__ descriptor does not support '_DictWrapper' objects

In [31]:
input_signature = [tf.TensorSpec([1, 224, 224, 3], tf.float32, name='x')]
onnx_model, _ = tf2onnx.convert.from_keras(model, input_signature)

In [10]:
onnx.save(onnx_model, "mobnet.onnx")

In [4]:
import onnx
import torch
from onnx2torch import convert

# Path to ONNX model
onnx_model_path = "model_weights/mobnet.onnx"
# You can pass the path to the onnx model to convert it or...
# torch_model_1 = convert(onnx_model_path)

# Or you can load a regular onnx model and pass it to the converter
onnx_model = onnx.load(onnx_model_path)
torch_model_2 = convert(onnx_model)

In [8]:
import torchvision

In [9]:
x = torchvision.io.read_image('data/0.jpg').permute(1, 2, 0)
scripted_module = torch.jit.script(torch_model_2, x)
# torch_model_2

c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\jit\_script.py:1291: UserWarning: `optimize` is deprecated and has no effect. Use `with torch.jit.optimized_execution() instead
  warnings.warn(
c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\jit\_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(


RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::eq.Tensor(Tensor self, Tensor other) -> Tensor:
  Expected a value of type 'Tensor' for argument 'self' but instead found type 'NoneType'.
  
  aten::eq.Scalar(Tensor self, Scalar other) -> Tensor:
  Expected a value of type 'Tensor' for argument 'self' but instead found type 'NoneType'.
  
  aten::eq.Scalar_out(Tensor self, Scalar other, *, Tensor(a!) out) -> Tensor(a!):
  Expected a value of type 'Tensor' for argument 'self' but instead found type 'NoneType'.
  
  aten::eq.Tensor_out(Tensor self, Tensor other, *, Tensor(a!) out) -> Tensor(a!):
  Expected a value of type 'Tensor' for argument 'self' but instead found type 'NoneType'.
  
  aten::eq.int_list(int[] a, int[] b) -> bool:
  Expected a value of type 'List[int]' for argument 'a' but instead found type 'NoneType'.
  
  aten::eq.device(Device a, Device b) -> bool:
  Expected a value of type 'Device' for argument 'a' but instead found type 'NoneType'.
  
  aten::eq.bool(bool a, bool b) -> bool:
  Expected a value of type 'bool' for argument 'a' but instead found type 'NoneType'.
  
  aten::eq.enum(AnyEnumType a, AnyEnumType b) -> bool:
  Expected a value of type 'AnyEnumType' for argument 'a' but instead found type 'NoneType'.
  
  aten::eq.int(int a, int b) -> bool:
  Expected a value of type 'int' for argument 'a' but instead found type 'NoneType'.
  
  aten::eq.complex(complex a, complex b) -> bool:
  Expected a value of type 'complex' for argument 'a' but instead found type 'NoneType'.
  
  aten::eq.float(float a, float b) -> bool:
  Expected a value of type 'float' for argument 'a' but instead found type 'NoneType'.
  
  aten::eq.int_float(int a, float b) -> bool:
  Expected a value of type 'int' for argument 'a' but instead found type 'NoneType'.
  
  aten::eq.float_int(float a, int b) -> bool:
  Expected a value of type 'float' for argument 'a' but instead found type 'NoneType'.
  
  aten::eq.float_complex(float a, complex b) -> bool:
  Expected a value of type 'float' for argument 'a' but instead found type 'NoneType'.
  
  aten::eq.complex_float(complex a, float b) -> bool:
  Expected a value of type 'complex' for argument 'a' but instead found type 'NoneType'.
  
  aten::eq(Scalar a, Scalar b) -> bool:
  Expected a value of type 'number' for argument 'a' but instead found type 'NoneType'.
  
  aten::eq.str(str a, str b) -> bool:
  Expected a value of type 'str' for argument 'a' but instead found type 'NoneType'.
  
  aten::eq.float_list(float[] a, float[] b) -> bool:
  Expected a value of type 'List[float]' for argument 'a' but instead found type 'NoneType'.
  
  aten::eq.Tensor_list(Tensor[] a, Tensor[] b) -> bool:
  Expected a value of type 'List[Tensor]' for argument 'a' but instead found type 'NoneType'.
  
  aten::eq.bool_list(bool[] a, bool[] b) -> bool:
  Expected a value of type 'List[bool]' for argument 'a' but instead found type 'NoneType'.
  
  aten::eq.str_list(str[] a, str[] b) -> bool:
  Expected a value of type 'List[str]' for argument 'a' but instead found type 'NoneType'.
  
  eq(float a, Tensor b) -> Tensor:
  Expected a value of type 'float' for argument 'a' but instead found type 'NoneType'.
  
  eq(int a, Tensor b) -> Tensor:
  Expected a value of type 'int' for argument 'a' but instead found type 'NoneType'.
  
  eq(complex a, Tensor b) -> Tensor:
  Expected a value of type 'complex' for argument 'a' but instead found type 'NoneType'.

The original call is:
  File "c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnx2torch\node_converters\binary_math_operations.py", line 47
        second: torch.Tensor,
    ) -> torch.Tensor:
        if self.broadcast == 1 and self.axis is not None:
           ~~~~~~~~~~~~~~~~~~~ <--- HERE
            second = old_style_broadcast(first, second, self.axis)
    


In [18]:
import onnxruntime as ort
import numpy as np
import cv2


img = cv2.imread('data/0.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img = img.astype(np.float32)
img[..., 0] -= 103.939
img[..., 1] -= 116.779
img[..., 2] -= 123.68
input1 = np.expand_dims(img, axis=0)
# img.shape
# # Change shapes and types to match model
# input1 = np.zeros((1, 100, 100, 3), np.float32)

# # Start from ORT 1.10, ORT requires explicitly setting the providers parameter if you want to use execution providers
# # other than the default CPU provider (as opposed to the previous behavior of providers getting set/registered by default
# # based on the build flags) when instantiating InferenceSession.
# # Following code assumes NVIDIA GPU is available, you can specify other execution providers or don't include providers parameter
# # to use default CPU provider.
sess = ort.InferenceSession("model_weights/mobnet.onnx", providers=["CPUExecutionProvider"])

# # Set first argument of sess.run to None to use all model outputs in default order
# # Input/output names are printed by the CLI and can be set with --rename-inputs and --rename-outputs
# # If using the python API, names are determined from function arg names or TensorSpec names.
results_ort = sess.run(["emotion_preds"], {"x": input1})

# import tensorflow as tf
# model = tf.saved_model.load("path/to/savedmodel")
# results_tf = model(input1)

# for ort_res, tf_res in zip(results_ort, results_tf):
#     np.testing.assert_allclose(ort_res, tf_res, rtol=1e-5, atol=1e-5)

# print("Results match")

In [20]:
input1.shape

(1, 224, 224, 3)

In [11]:
import numpy as np

In [35]:
input_shape

array([  1, 224, 224,   3])

In [36]:
interpreter = tf.lite.Interpreter('model_weights/saved_model/mobnet_float32.tflite')
# Load the TFLite model and allocate tensors.
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test the model on random input data.
# input_shape = input_details[0]['shape']
# input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
input_data = input1
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)

[[0.00333038 0.00210853 0.0254259  0.513841   0.32844743 0.02245985
  0.1043869 ]]


In [37]:
results_ort

[array([[0.00333036, 0.00210852, 0.02542585, 0.5138409 , 0.32844752,
         0.02245977, 0.10438711]], dtype=float32)]

In [25]:
model(input1)

<tf.Tensor: shape=(1, 7), dtype=float32, numpy=
array([[0.00333036, 0.00210853, 0.02542588, 0.5138411 , 0.32844722,
        0.02245977, 0.10438712]], dtype=float32)>

In [26]:
results_ort

[array([[0.00333036, 0.00210852, 0.02542585, 0.5138409 , 0.32844752,
         0.02245977, 0.10438711]], dtype=float32)]

In [22]:
np.argmax(results_ort[0])

3

In [23]:
idx_to_class={0: 'Anger', 1: 'Disgust', 2: 'Fear', 3: 'Happiness', 4: 'Neutral', 5: 'Sadness', 6: 'Surprise'}


In [28]:
import onnx
from onnx2pytorch import ConvertModel

In [32]:
pytorch_model = ConvertModel(onnx_model)

c:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnx2pytorch\convert\layer.py:30: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:212.)
  layer.weight.data = torch.from_numpy(numpy_helper.to_array(weight))


In [36]:
pytorch_model

ConvertModel(
  (Transpose_model_2_1/conv1_bn_1/batchnorm/mul_1__306:0): Transpose()
  (Conv_Conv__459:0): Sequential(
    (0): ConstantPad2d(padding=(0, 1, 0, 1), value=0)
    (1): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2))
  )
  (Clip_model_2_1/conv1_relu_1/Relu6:0): Clip()
  (Conv_model_2_1/conv_dw_1_1/depthwise:0): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
  (Mul_model_2_1/conv_dw_1_bn_1/batchnorm/mul_1:0): mul()
  (Add_model_2_1/conv_dw_1_bn_1/batchnorm/add_1:0): Add()
  (Clip_model_2_1/conv_dw_1_relu_1/Relu6:0): Clip()
  (Conv_Conv__466:0): Conv2d(32, 64, kernel_size=(1, 1), stride=(1, 1))
  (Clip_model_2_1/conv_pw_1_relu_1/Relu6:0): Clip()
  (Pad_model_2_1/conv_pad_2_1/Pad:0): Pad(mode=constant, padding=None)
  (Conv_model_2_1/conv_dw_2_1/depthwise:0): Conv2d(64, 64, kernel_size=(3, 3), stride=(2, 2), groups=64, bias=False)
  (Mul_model_2_1/conv_dw_2_bn_1/batchnorm/mul_1:0): mul()
  (Add_model_2_1/conv_dw_2_bn_1/batchnorm/add_

In [38]:
pytorch_model.state_dict()

OrderedDict([('_initializer_pad_const__323', tensor([0, 0, 0, 0, 0, 0, 1, 1])),
             ('_initializer_model_2_1/feats_1/Cast/ReadVariableOp:0',
              tensor([[ 1.1598e-30, -8.3261e-02,  1.5456e-01,  ..., -7.9706e-31,
                        1.4436e-30,  3.6998e-02],
                      [ 1.3932e-30, -7.2393e-02,  7.2119e-02,  ...,  8.6144e-31,
                       -3.9486e-31,  3.5457e-02],
                      [ 6.5584e-31, -6.0286e-03,  2.4674e-02,  ..., -1.4369e-30,
                       -1.3923e-30, -3.7752e-02],
                      ...,
                      [-3.2552e-31, -4.8425e-02,  2.0235e-02,  ...,  8.1769e-31,
                        1.2445e-30,  9.5486e-02],
                      [ 4.5851e-31, -9.7732e-02, -5.9737e-02,  ...,  1.0508e-32,
                       -8.7902e-31, -9.7152e-02],
                      [-1.1596e-30, -5.3769e-02, -3.3375e-03,  ..., -7.4846e-31,
                        2.2500e-31, -3.4877e-02]])),
             ('_initializer_model_

In [13]:
load_model('model_weights/age_gender_ethnicity_224_deep-03-0.13-0.97-0.88.pb')

ValueError: File format not supported: filepath=model_weights/age_gender_ethnicity_224_deep-03-0.13-0.97-0.88.pb. Keras 3 only supports V3 `.keras` files and legacy H5 format files (`.h5` extension). Note that the legacy SavedModel format is not supported by `load_model()` in Keras 3. In order to reload a TensorFlow SavedModel as an inference-only layer in Keras 3, use `keras.layers.TFSMLayer(model_weights/age_gender_ethnicity_224_deep-03-0.13-0.97-0.88.pb, call_endpoint='serving_default')` (note that your `call_endpoint` might have a different name).